_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 12
                - 45
                - 55
            "2":
                - 1
                - 12
                - 45
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 34
                - 55
            "4": 3.10.16
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
ACTIVATION:
    value: relu
ACTOR_LR:
    value: 0.0003
ANNEAL_LR:
    value: false
CLIP_EPS:
    value: 0.2
CRITIC_LR:
    value: 0.003
DEBUG:
    value: true
EGO_OBS_DIM:
    value: 5
ENT_COEF:
    value: 0.001
FC_DIM_SIZE:
    value: 256
FOR_LOOP_EPOCHS:
    value: 15
GAE_LAMBDA:
    value: 0.95
GAMMA:
    value: 0.995
GLOBAL_OBS_DIM:
    value: "37"
GROUP:
    value: combat_hierarchy_pitch
GRU_HIDDEN_DIM:
    value: 256
LOGDIR:
    value: results/combat_hierarchy_pitch_2025-07-07-16-32/logs
MAX_GRAD_NORM:
    value: 0.5
NOISE_SEED:
    value: 42
NUM_ACTORS:
    value: 4
NUM_ENVS:
    value: 500
NUM_MINIBATCHES:
    value: 4
NUM_STEPS:
    value: 1500
NUM_UPDATES:
    value: 133
NUM_VALID_AGENTS:
    value: 2
OBS_DIM:
    value: "23"
OTHER_OBS_DIM:
    value: 6
OUTPUTDIR:
    value: results/combat_hierarchy_pitch_2025-07-07-16-32
REWARD_NORM:
    value: false
REWARD_NORM_CLIP:
    value: 10
REWARD_NORM_EPSILON:
    value: 1e-08
REWARD_NORM_GAMMA:
    value: 0.99
RNN_GRAD_CLIP_VALUE:
    value: 0.5
SAVEDIR:
    value: results/combat_hierarchy_pitch_2025-07-07-16-32/checkpoints
SEED:
    value: 42
TOTAL_TIMESTEPS:
    value: 1e+08
TRAIN:
    value: true
UPDATE_EPOCHS:
    value: 8
VF_COEF:
    value: 1
WANDB:
    value: true
WANDB_API_KEY:
    value: 4c0cc04699296bed768adea4824fbaecea35dc59
